version: '3.8'

services:
  api:
    build: ./go-server
    ports:
      - "8080:8080"
    depends_on:
      - influxdb
    env_file:
      - .env

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=reactors
      - DOCKER_INFLUXDB_INIT_BUCKET=reactor_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-token

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards/reactor1.json:/var/lib/grafana/dashboards/reactor1.json
      - ./grafana/dashboards/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/datasources/influxdb.yaml:/etc/grafana/provisioning/datasources/influxdb.yaml
    depends_on:
      - influxdb

volumes:
  influxdb-data:
  grafana-data:


