{
 "title": "Reactor 1",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Energy Buffer over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MRF" } },
   "targets": [
    {
     "query": "from(bucket: \"reactor_data\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"reactor\" and r._field == \"energy_stored\")\n  |> map(fn: (r) => ({ r with _value: r._value / 1000000.0 }))"
    }
   ]
  },
  {
   "title": "Reactor Buffer",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MRF" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"reactor_data\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"reactor\" and r._field == \"energy_stored\")\n  |> map(fn: (r) => ({ r with _value: r._value / 1000000.0 }))"
    }
   ]
  },
  {
   "title": "Energy Produced over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "MRF" } },
   "targets": [
    {
     "query": "from(bucket: \"reactor_data\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"reactor\" and r._field == \"energy_produced\")\n  |> map(fn: (r) => ({ r with _value: r._value / 1000000.0 }))"
    }
   ]
  },
  {
   "title": "Energy Production",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "KRF/t" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"reactor_data\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"reactor\" and r._field == \"energy_produced\")\n  |> map(fn: (r) => ({ r with _value: r._value / 1000.0 }))"
    }
   ]
  },
  {
   "title": "Fuel Used over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Litre/t" } },
   "targets": [
    {
     "query": "from(bucket:\"reactor_data\")\n  |> range(start:-1h)\n  |> filter(fn:(r)=>r._measurement==\"reactor\" and r._field==\"fuel_used\")"
    }
   ]
  },
  {
   "title": "Reactor Fuel Used",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Litre/t" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"reactor_data\")\n  |> range(start:-1h)\n  |> filter(fn:(r)=>r._measurement==\"reactor\" and r._field==\"fuel_used\")"
    }
   ]
  },
  {
   "title": "Fuel Amount over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "query": "from(bucket: \"reactor_data\")\n  |> range(start: -1h)\n  |> filter(fn: (r) =>\n    r._measurement == \"reactor\" and\n    r._field == \"fuel_amount\"\n  )\n  |> toFloat()    // converts _value to float\n  |> map(fn: (r) => ({ r with _value: r._value / 1000.0 }))\n"
    }
   ]
  },
  {
   "title": "Reactor Fuel Amount",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"reactor_data\")\n  |> range(start: -1h)\n  |> filter(fn: (r) =>\n    r._measurement == \"reactor\" and\n    r._field == \"fuel_amount\"\n  )\n  |> toFloat()    // converts _value to float\n  |> map(fn: (r) => ({ r with _value: r._value / 1000.0 }))\n"
    }
   ]
  },
  {
   "title": "Fuel Temperature over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "°C" } },
   "targets": [
    {
     "query": "from(bucket: \"reactor_data\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"reactor\" and r._field == \"fuel_temp\")"
    }
   ]
  },
  {
   "title": "Reactor Fuel Temp",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "°C" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"reactor_data\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"reactor\" and r._field == \"fuel_temp\")"
    }
   ]
  },
  {
   "title": "Casing Temperature over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "°C" } },
   "targets": [
    {
     "query": "from(bucket:\"reactor_data\")\n  |> range(start:-1h)\n  |> filter(fn:(r)=>r._measurement==\"reactor\" and r._field==\"casing_temp\")"
    }
   ]
  },
  {
   "title": "Reactor Casing Temp",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "°C" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"reactor_data\")\n  |> range(start:-1h)\n  |> filter(fn:(r)=>r._measurement==\"reactor\" and r._field==\"casing_temp\")"
    }
   ]
  },
  {
   "title": "Waste Amount over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "query": "from(bucket:\"reactor_data\")\n  |> range(start:-1h)\n  |> filter(fn:(r)=>r._measurement==\"reactor\" and r._field==\"waste_amount\")"
    }
   ]
  },
  {
   "title": "Reactivity over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 70 },
   "targets": [
    {
     "query": "from(bucket:\"reactor_data\")\n  |> range(start:-1h)\n  |> filter(fn:(r)=>r._measurement==\"reactor\" and r._field==\"reactivity\")"
    }
   ]
  },
  {
   "title": "Reactor Reactivity",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"reactor_data\")\n  |> range(start:-1h)\n  |> filter(fn:(r)=>r._measurement==\"reactor\" and r._field==\"reactivity\")"
    }
   ]
  },
  {
   "title": "Rod Insertion over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "query": "from(bucket:\"reactor_data\")\n  |> range(start:-1h)\n  |> filter(fn:(r)=>r._measurement==\"reactor\" and r._field==\"rod_insertion\")"
    }
   ]
  },
  {
   "title": "Control Rod Insertion",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"reactor_data\")\n  |> range(start:-1h)\n  |> filter(fn:(r)=>r._measurement==\"reactor\" and r._field==\"rod_insertion\")"
    }
   ]
  }
 ]
}