apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    uid: influxdb
    orgId: 1
    url: http://influxdb:8086
    basicAuth: false
    jsonData:
      version: Flux
      organization: reactors
      defaultBucket: reactor_data
    secureJsonData:
      token: my-super-token
    isDefault: true

